### ISSUE TITLE
Time consuming of "Subgraph Pattern Encoding"

### ISSUE THREAD

**Issue by chao92** [muhanzhang/LinkPrediction#2]
Hi,

Do you have any idea of how to accelerating the process of "subgraph pattern encoding"?

Best,

Chao

**Comment by muhanzhang** [comment]
If you are using the Python version, you can limit the number of nodes per hop by appending “--max-nodes-per-hop 100” and set the number of hops to be only 1 by appending “--hop 1”.
 
Also, you may also limit the number of training links to use (it is not necessary to use all observed links as training data and extract enclosing subgraphs, a portion of them might be enough). Try to append “--max-train-num 1000”.

**Comment by muhanzhang** [comment]
Hi, please check this repository https://github.com/muhanzhang/SEAL/tree/master/MATLAB

It contains a slightly improved WLNM implementation. In particular, please check the `graph2vector.m` in that repository. You can uncomment line 31 and change line 32 from `for` to `parfor` to enable parallel computing of the subgraph pattern encoding step.
